title: Dynamo Developer Page
description: Learn how to code, develop, and share your own Dynamo tools.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Primary Site URLs

dynamo: "http://dynamobim.org"
forums: "https://forum.dynamobim.com"
twitter: "https://twitter.com/DynamoBIM"
facebook: "https://www.facebook.com/DynamoBIM"

# Resources

# Core Library

dynamo_primer: "#"
dynamo_dictionary: "#"
dynamo_blog: "#"

# Code Block

intro_to_code_block: "#"
designscript_guide: "#"
designscript_doc: "#"

# Python

python_in_dynamo: "#"

# Third-Party libraries

dynamo_package_manager: "#"
installing_packages: "#"

# Node and Package Development

developing_nodes: "#"
developing_packages: "#"

# Customizing with Dynamo

create_custom_nodes: "#"

# Customizing with C# with Visual Studio - Zero-Touch

dynamo_api: "#"
zero_touch_development: "#"
nodes_with_custom_ui: "#"
developing_c_sharp_packages: "#"

# Publishing your work

publishing_a_package: "#"
example_packages: "#"

# More

dynamo_wiki: "#"


# Build settings
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']
permalink: /:title/
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
